# -*- coding: utf-8 -*-
# Script to replace topic 10 subtopics with expanded content
import os

with open('seed_database.py', 'r', encoding='utf-8', errors='replace') as f:
    content = f.read()

# Find positions
old_10_1_start = content.find('"id": "sub-10-1"')
block_start_10_1 = content.rfind('{', 0, old_10_1_start)

old_10_2_start = content.find('"id": "sub-10-2"')
block_start_10_2 = content.rfind('{', 0, old_10_2_start)

old_10_3_start = content.find('"id": "sub-10-3"')
block_start_10_3 = content.rfind('{', 0, old_10_3_start)

# Find end of sub-10-3 block (the closing }, before ],)
end_marker = content.find('},\n        ],\n    },\n]', block_start_10_3)
end_of_all_subs = end_marker + len('},')  # include the closing },

print(f"Replacing from pos {block_start_10_1} to {end_of_all_subs}")

new_subtopics = r'''            {
                "id": "sub-10-1", "name": "Selecting Elements",
                "pdfUrl": "internal", "pdfTitle": "DOM Selecting Elements",
                "overview": "JavaScript provides several methods to find HTML elements in the DOM tree. querySelector() is the most versatile, accepting any CSS selector and returning the first matching element (or null). querySelectorAll() returns a static NodeList of all matches. getElementById() is the fastest method for finding elements by their ID attribute, using an O(1) hash table lookup internally. getElementsByClassName() and getElementsByTagName() return live HTMLCollections that automatically update when the DOM changes. Understanding when to use static vs live collections, and how to convert NodeLists to arrays for array methods, is essential for effective DOM manipulation.",
                "explanations": [
                    {"style": "simplified", "title": "Simplified", "icon": "\ud83d\udcdd", "content": "To interact with HTML elements using JavaScript, you first need to select them. querySelector() is the go-to method because it accepts any CSS selector you already know: IDs (#myId), classes (.myClass), tags (div), and complex selectors (div > p.intro). It returns the first matching element or null if nothing matches. querySelectorAll() finds ALL matching elements and returns a NodeList you can loop through with forEach(). getElementById() is fastest when you know the exact ID. Always check if your selection returned null before trying to modify the element, or you will get a TypeError.", "codeExample": "// querySelector: the most flexible selector\nconst header = document.querySelector('#main-header');\nconst firstBtn = document.querySelector('.btn-primary');\nconst firstPara = document.querySelector('article > p');\n\n// querySelectorAll: find ALL matches\nconst allCards = document.querySelectorAll('.card');\nconsole.log(allCards.length);  // number of cards\nallCards.forEach(card => {\n    console.log(card.textContent);\n});\n\n// getElementById: fastest for IDs\nconst nav = document.getElementById('navbar');\n\n// Always check for null!\nconst el = document.querySelector('.maybe-missing');\nif (el) {\n    el.textContent = 'Found it!';\n}"},
                    {"style": "logical", "title": "Logical", "icon": "\ud83e\udde0", "content": "document.querySelector(selector) performs a depth-first pre-order traversal of the DOM tree, matching against CSS selectors. It returns the first matching Element or null. querySelectorAll() returns a static NodeList (snapshot at call time, does not update). getElementById() uses an internal hash map for O(1) lookup by ID. getElementsByClassName() and getElementsByTagName() return live HTMLCollections that reflect DOM changes in real time. NodeList supports forEach() but not map() or filter() directly; convert with Array.from(nodeList) or [...nodeList] to use array methods. Scoped queries are possible: element.querySelector() searches only within that element's subtree.", "codeExample": "// Static vs live collections\nconst staticList = document.querySelectorAll('li');\nconst liveList = document.getElementsByTagName('li');\n\nconsole.log(staticList.length); // e.g., 5\nconsole.log(liveList.length);   // e.g., 5\n\n// Add a new <li> to the DOM\nconst newLi = document.createElement('li');\ndocument.querySelector('ul').appendChild(newLi);\n\nconsole.log(staticList.length); // still 5 (snapshot)\nconsole.log(liveList.length);   // now 6 (live!)\n\n// Convert NodeList to Array for array methods\nconst items = [...document.querySelectorAll('.item')];\nconst texts = items.map(el => el.textContent);\n\n// Scoped query: search within a specific element\nconst sidebar = document.querySelector('#sidebar');\nconst sideLinks = sidebar.querySelectorAll('a');"},
                    {"style": "visual", "title": "Visual", "icon": "\ud83c\udfa8", "content": "DOM Tree:\n  document\n    |-- html\n         |-- head\n         |-- body\n              |-- div#header\n              |    |-- h1.title\n              |    |-- nav\n              |         |-- a.link\n              |         |-- a.link.active\n              |-- main\n                   |-- p\n                   |-- p.intro\n\nquerySelector('.link')       -> first a.link\nquerySelectorAll('.link')    -> NodeList[a.link, a.link.active]\nquerySelector('.link.active') -> a.link.active\nquerySelector('#header h1')  -> h1.title", "codeExample": "// Practical: highlight all links in a specific section\nconst nav = document.querySelector('nav');\nconst navLinks = nav.querySelectorAll('a');\n\nnavLinks.forEach((link, index) => {\n    console.log(`Link ${index}: ${link.href}`);\n});\n\n// Find elements by data attribute\nconst activeTab = document.querySelector('[data-tab=\"home\"]');\nconst allTabs = document.querySelectorAll('[data-tab]');\n\n// Complex CSS selectors work too\nconst el = document.querySelector(\n    'div.container > ul li:first-child'\n);"},
                    {"style": "analogy", "title": "Analogy", "icon": "\ud83d\udd17", "content": "Selecting DOM elements is like using a spotlight on a theater stage. getElementById() is like calling an actor by their unique stage name: instant and precise, there is only one actor with that name. querySelector() is like describing the actor you want: 'the one wearing a red hat in the second row' (CSS selector). The spotlight crew searches the stage and finds the first match. querySelectorAll() tells the spotlight crew to find ALL actors matching your description and line them up. A live collection (getElementsByClassName) is a magic list that updates itself whenever actors join or leave the stage. A static NodeList is a photograph: it shows who was there when you took it.", "codeExample": "// Spotlight analogy: finding actors on stage\n\n// By unique name (ID) - instant\nconst hero = document.getElementById('protagonist');\n\n// By description (CSS selector) - first match\nconst villain = document.querySelector('.character.evil');\n\n// All matching the description\nconst allExtras = document.querySelectorAll('.extra');\nconsole.log(`${allExtras.length} extras on stage`);\n\n// Narrow the search to a specific scene\nconst scene2 = document.querySelector('#scene-2');\nconst scene2Actors = scene2.querySelectorAll('.character');"},
                ],
                "quiz": [
                    {"id": "q10-1-1", "question": "What does querySelector return if no match?", "options": ["undefined", "An empty element", "null", "An error"], "correctAnswer": 2},
                    {"id": "q10-1-2", "question": "What does querySelectorAll return?", "options": ["A single element", "An array", "A NodeList", "A string"], "correctAnswer": 2},
                    {"id": "q10-1-3", "question": "Which selector method is fastest for IDs?", "options": ["querySelector", "querySelectorAll", "getElementById", "getElementsByTagName"], "correctAnswer": 2},
                ],
                "recommendedVideos": [{"id": "vid-12", "title": "JavaScript DOM Crash Course", "language": "JavaScript", "youtubeId": "0ik6X4DJKCc", "thumbnail": "https://img.youtube.com/vi/0ik6X4DJKCc/mqdefault.jpg", "duration": "28:30"}],
            },
            {
                "id": "sub-10-2", "name": "Modifying Elements",
                "pdfUrl": "internal", "pdfTitle": "DOM Modifying Elements",
                "overview": "Once you have selected a DOM element, JavaScript lets you modify its content, styles, attributes, and CSS classes. textContent safely sets plain text (immune to XSS). innerHTML parses and sets HTML markup (use with caution as it can introduce XSS vulnerabilities if used with user input). The style property sets inline CSS styles. classList provides methods like add(), remove(), toggle(), and contains() for managing CSS classes cleanly. setAttribute() and getAttribute() work with any HTML attribute. The dataset property provides convenient access to data-* custom attributes. createElement() and appendChild() let you build and insert new elements into the DOM.",
                "explanations": [
                    {"style": "simplified", "title": "Simplified", "icon": "\ud83d\udcdd", "content": "After selecting an element, you can change almost everything about it. textContent changes the text inside an element safely (it will not execute any HTML or scripts). innerHTML can set HTML markup inside an element, but be careful: never put user input directly into innerHTML or it could run malicious scripts (XSS attack). style lets you change CSS properties directly: el.style.backgroundColor = 'blue'. classList is the cleanest way to manage CSS classes: add(), remove(), toggle() a class on or off, and contains() to check if a class exists. createElement() builds new elements, and appendChild() or append() adds them to the page.", "codeExample": "const card = document.querySelector('.card');\n\n// Safe text change\ncard.textContent = 'Hello World!';\n\n// HTML change (be careful with user input!)\ncard.innerHTML = '<strong>Bold text</strong>';\n\n// Style changes\ncard.style.backgroundColor = '#1a1a2e';\ncard.style.padding = '20px';\ncard.style.borderRadius = '12px';\n\n// Class management (preferred over direct style)\ncard.classList.add('active', 'highlighted');\ncard.classList.remove('hidden');\ncard.classList.toggle('dark-mode');\nconsole.log(card.classList.contains('active')); // true\n\n// Create and append new elements\nconst badge = document.createElement('span');\nbadge.textContent = 'NEW';\nbadge.classList.add('badge');\ncard.appendChild(badge);"},
                    {"style": "logical", "title": "Logical", "icon": "\ud83e\udde0", "content": "textContent sets the text node content without HTML parsing, making it XSS-safe. innerHTML triggers the HTML parser and can execute scripts embedded in the markup, so never use it with unsanitized user input. innerText is similar to textContent but respects CSS visibility (slower due to layout computation). The style property accesses CSSStyleDeclaration for inline styles; camelCase is used (backgroundColor, not background-color). classList is a DOMTokenList supporting add(), remove(), toggle(class, force?), contains(), and replace(oldClass, newClass). setAttribute(name, value) and getAttribute(name) handle any HTML attribute. dataset provides a DOMStringMap for data-* attributes: data-user-id becomes element.dataset.userId.", "codeExample": "const el = document.querySelector('#profile');\n\n// Attributes\nel.setAttribute('role', 'button');\nel.setAttribute('aria-label', 'User profile');\nconsole.log(el.getAttribute('role')); // 'button'\n\n// Data attributes\nel.dataset.userId = '42';     // sets data-user-id=\"42\"\nel.dataset.status = 'active'; // sets data-status=\"active\"\nconsole.log(el.dataset.userId); // '42'\n\n// Building DOM elements programmatically\nconst ul = document.createElement('ul');\nconst fruits = ['Apple', 'Banana', 'Cherry'];\n\nfruits.forEach(fruit => {\n    const li = document.createElement('li');\n    li.textContent = fruit;\n    li.classList.add('fruit-item');\n    ul.appendChild(li);\n});\n\ndocument.querySelector('#list-container').appendChild(ul);"},
                    {"style": "visual", "title": "Visual", "icon": "\ud83c\udfa8", "content": "Before modification:\n<div class=\"card\">\n  <p>Original text</p>\n</div>\n\nAfter el.textContent = 'New text':\n<div class=\"card\">New text</div>\n(all children replaced with text node)\n\nAfter el.innerHTML = '<p>New <b>HTML</b></p>':\n<div class=\"card\"><p>New <b>HTML</b></p></div>\n(HTML parsed and inserted)\n\nAfter el.classList.add('active'):\n<div class=\"card active\">...</div>\n\nAfter el.style.color = 'red':\n<div class=\"card active\" style=\"color: red;\">...</div>", "codeExample": "// Practical: toggle dark mode\nconst toggleBtn = document.querySelector('#theme-toggle');\nconst body = document.body;\n\ntoggleBtn.addEventListener('click', () => {\n    body.classList.toggle('dark-mode');\n    const isDark = body.classList.contains('dark-mode');\n    toggleBtn.textContent = isDark ? 'Light Mode' : 'Dark Mode';\n});\n\n// Practical: build a card dynamically\nfunction createCard(title, description) {\n    const card = document.createElement('div');\n    card.classList.add('card');\n\n    const h3 = document.createElement('h3');\n    h3.textContent = title;  // safe from XSS\n\n    const p = document.createElement('p');\n    p.textContent = description;\n\n    card.appendChild(h3);\n    card.appendChild(p);\n    return card;\n}"},
                    {"style": "analogy", "title": "Analogy", "icon": "\ud83d\udd17", "content": "Modifying DOM elements is like customizing a puppet in a puppet show. textContent is changing what the puppet says (its dialogue). innerHTML is rewriting the puppet's entire script, which is powerful but dangerous if the script comes from an untrusted stranger (XSS). style is changing the puppet's costume directly: new hat, new color. classList is like adding or removing accessories: add a cape (classList.add), remove the mask (classList.remove), or toggle the hat on and off (classList.toggle). createElement and appendChild are building a brand new puppet and placing it on the stage next to the others.", "codeExample": "// Puppet customization analogy\nconst puppet = document.querySelector('.puppet');\n\n// Change dialogue (safe)\npuppet.textContent = 'Hello, audience!';\n\n// Change costume\npuppet.style.color = 'gold';\npuppet.style.fontSize = '24px';\n\n// Add accessories\npuppet.classList.add('cape', 'crown');\npuppet.classList.remove('mask');\npuppet.classList.toggle('hat');\n\n// Build a new puppet and add to stage\nconst newPuppet = document.createElement('div');\nnewPuppet.classList.add('puppet', 'villain');\nnewPuppet.textContent = 'I am the villain!';\ndocument.querySelector('#stage').appendChild(newPuppet);"},
                ],
                "quiz": [
                    {"id": "q10-2-1", "question": "Which is safer: textContent or innerHTML?", "options": ["innerHTML", "textContent", "Both are equal", "Neither is safe"], "correctAnswer": 1},
                    {"id": "q10-2-2", "question": "What does classList.toggle() do?", "options": ["Adds a class", "Removes a class", "Adds if absent, removes if present", "Clears all classes"], "correctAnswer": 2},
                    {"id": "q10-2-3", "question": "How do you change an element's background color?", "options": ["el.color = 'red'", "el.style.backgroundColor = 'red'", "el.bg = 'red'", "el.css('bg', 'red')"], "correctAnswer": 1},
                ],
                "recommendedVideos": [{"id": "vid-12", "title": "JavaScript DOM Crash Course", "language": "JavaScript", "youtubeId": "0ik6X4DJKCc", "thumbnail": "https://img.youtube.com/vi/0ik6X4DJKCc/mqdefault.jpg", "duration": "28:30"}],
            },
            {
                "id": "sub-10-3", "name": "Event Handling",
                "pdfUrl": "internal", "pdfTitle": "DOM Event Handling Guide",
                "overview": "Event handling is how JavaScript responds to user interactions like clicks, key presses, form submissions, and mouse movements. addEventListener(type, callback) attaches an event handler to an element. Events propagate through three phases: capture (top-down from document to target), target (the element itself), and bubble (bottom-up from target to document). Event delegation leverages bubbling by attaching a single listener to a parent element and using event.target to determine which child was clicked, which is far more efficient than attaching listeners to every child. event.preventDefault() stops the browser's default action (like form submission), and event.stopPropagation() prevents the event from bubbling further up.",
                "explanations": [
                    {"style": "simplified", "title": "Simplified", "icon": "\ud83d\udcdd", "content": "addEventListener lets you run a function when something happens to an element, like a click, key press, or form submission. The first argument is the event type ('click', 'input', 'submit', 'keydown'), and the second is your handler function that runs when the event fires. Events bubble up from the clicked element to its parents, which means a click on a button inside a div also triggers click handlers on the div. Event delegation takes advantage of this: instead of adding a click listener to every list item, add one listener to the parent ul and check event.target to see which item was clicked. Use event.preventDefault() to stop default browser behavior like following a link or submitting a form.", "codeExample": "// Basic click handler\nconst btn = document.querySelector('#myButton');\nbtn.addEventListener('click', function(event) {\n    console.log('Button clicked!');\n    console.log('Clicked element:', event.target);\n});\n\n// Form submit with preventDefault\nconst form = document.querySelector('#myForm');\nform.addEventListener('submit', (e) => {\n    e.preventDefault();  // stop page refresh\n    const name = form.querySelector('#name').value;\n    console.log('Form submitted:', name);\n});\n\n// Input event for real-time updates\nconst search = document.querySelector('#search');\nsearch.addEventListener('input', (e) => {\n    console.log('Typing:', e.target.value);\n});"},
                    {"style": "logical", "title": "Logical", "icon": "\ud83e\udde0", "content": "addEventListener(type, callback, options) attaches event handlers. The options parameter can be a boolean (useCapture) or an object {capture, once, passive}. Event propagation has three phases: capture (document to target), target phase, and bubble (target to document). event.stopPropagation() halts propagation. event.stopImmediatePropagation() also prevents other handlers on the same element. event.preventDefault() cancels the default browser action (navigation, form submit, text selection). Event delegation uses bubbling: attach one O(1) listener on a parent instead of O(n) listeners on children. Use event.target for the actual clicked element and event.currentTarget for the element the listener is on. removeEventListener requires the same function reference to detach.", "codeExample": "// Event delegation: one listener for many items\nconst todoList = document.querySelector('#todo-list');\n\ntodoList.addEventListener('click', (e) => {\n    if (e.target.classList.contains('delete-btn')) {\n        e.target.closest('li').remove();\n    }\n    if (e.target.classList.contains('todo-text')) {\n        e.target.classList.toggle('completed');\n    }\n});\n\n// Capture vs bubble phase\ndocument.querySelector('#outer').addEventListener('click',\n    () => console.log('Outer - capture'), true);\ndocument.querySelector('#inner').addEventListener('click',\n    () => console.log('Inner - bubble'));\n// Click inner: 'Outer - capture' then 'Inner - bubble'\n\n// {once: true} auto-removes after first trigger\nbtn.addEventListener('click', () => {\n    console.log('This only fires once!');\n}, {once: true});"},
                    {"style": "visual", "title": "Visual", "icon": "\ud83c\udfa8", "content": "Event propagation phases:\n\n         document    (1) CAPTURE phase: top-down\n           |              document -> body -> div -> button\n          body\n           |         (2) TARGET phase: the clicked element\n          div              button fires its handlers\n           |\n         button      (3) BUBBLE phase: bottom-up\n       [CLICKED]          button -> div -> body -> document\n\nEvent delegation:\n  <ul id='list'>          <- ONE listener here\n    <li>Item 1</li>       <- click bubbles up to ul\n    <li>Item 2</li>       <- event.target tells us which li\n    <li>Item 3</li>\n  </ul>", "codeExample": "// Dynamic list with event delegation\nconst list = document.querySelector('#item-list');\nconst addBtn = document.querySelector('#add-item');\n\n// One listener handles ALL items (even future ones!)\nlist.addEventListener('click', (e) => {\n    const li = e.target.closest('li');\n    if (!li) return;\n\n    console.log('Clicked:', li.textContent);\n    li.classList.toggle('selected');\n});\n\n// Adding new items - they work automatically!\nlet count = 0;\naddBtn.addEventListener('click', () => {\n    const li = document.createElement('li');\n    li.textContent = `Item ${++count}`;\n    list.appendChild(li);\n    // No need to add a new event listener!\n});"},
                    {"style": "analogy", "title": "Analogy", "icon": "\ud83d\udd17", "content": "Event handling is like a doorbell system in an apartment building. addEventListener is installing a doorbell (listener) on a specific door (element). When a visitor presses the doorbell (event occurs), your handler function answers. Event bubbling is like sound traveling: when someone rings Apartment 3A's bell, the sound travels up through the floor (parent elements) to the whole building. Event delegation is like having ONE security guard at the building entrance instead of a guard at every apartment door. The guard checks who the visitor wants to see (event.target) and handles it. This is much more efficient, especially when apartments (child elements) are constantly added or removed.", "codeExample": "// Building security analogy\n\n// BAD: guard at every door (inefficient)\nconst apartments = document.querySelectorAll('.apartment');\napartments.forEach(apt => {\n    apt.addEventListener('click', (e) => {\n        console.log('Visited:', apt.id);\n    });\n}); // O(n) listeners!\n\n// GOOD: one guard at the entrance (event delegation)\nconst building = document.querySelector('#building');\nbuilding.addEventListener('click', (e) => {\n    const apt = e.target.closest('.apartment');\n    if (apt) {\n        console.log('Visited:', apt.id);\n    }\n}); // O(1) listener!\n\n// Works for new apartments added later!\nconst newApt = document.createElement('div');\nnewApt.classList.add('apartment');\nnewApt.id = 'apt-new';\nbuilding.appendChild(newApt);"},
                ],
                "quiz": [
                    {"id": "q10-3-1", "question": "What does addEventListener do?", "options": ["Creates an element", "Attaches an event handler to an element", "Removes an element", "Modifies styles"], "correctAnswer": 1},
                    {"id": "q10-3-2", "question": "What is event delegation?", "options": ["Attaching listeners to every child", "Listening on a parent and checking the target", "Removing all events", "Creating custom events"], "correctAnswer": 1},
                    {"id": "q10-3-3", "question": "What does event.preventDefault() do?", "options": ["Stops event bubbling", "Prevents the default browser action", "Removes the listener", "Creates a new event"], "correctAnswer": 1},
                ],
                "recommendedVideos": [{"id": "vid-12", "title": "JavaScript DOM Crash Course", "language": "JavaScript", "youtubeId": "0ik6X4DJKCc", "thumbnail": "https://img.youtube.com/vi/0ik6X4DJKCc/mqdefault.jpg", "duration": "28:30"}],
            },'''

# Now do the replacement
new_content = content[:block_start_10_1] + new_subtopics + content[end_of_all_subs:]

with open('seed_database.py', 'w', encoding='utf-8') as f:
    f.write(new_content)

print("SUCCESS: Topic 10 subtopics expanded!")
print(f"Old size: {len(content)} chars")
print(f"New size: {len(new_content)} chars")

# Verify
with open('seed_database.py', 'r', encoding='utf-8') as f:
    verify = f.read()
count = verify.count('codeExample')
print(f"Total codeExample occurrences in file: {count}")
